spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.229.60:3306/worldcup_mgmt
    username: root
    password: sw1234!
  thymeleaf:
    cache: true

#server인증서 적용 설정 -> https
#server:
#  port: 443 - https 포트 번호
#  ssl:
#    enabled: true
#    key-alias: 

#spring:
#  datasource:
#    url:  jdbc:h2:~/test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    initialization-mode: always
#    schema: classpath:h2/schema.sql
#    data: classpath:h2/data.sql
#  h2:
#    console:
#      enabled: true
#      path: /h2-console